Website = "https://github.com/azorg/fyneterm"

[Details]
  Icon = "Icon.png"
  Name = "fyneterm"
  ID = "com.example.fyneterm"
  Version = "1.0.0"
  Build = 7

[LinuxAndBSD]
  GenericName = "fyneterm"
  Categories = ["stuff"]
  Comment = "Fyne terminal"
  Keywords = ["fyne", "terminal", "example"]
